stages:
  clean:
    cmd: python src/preprocessing/clean.py
    deps:
      - data/raw/data.csv
      - src/preprocessing/clean.py
    outs:
      - data/processed/data_cleaned.csv

  encode:
    cmd: python src/preprocessing/encode.py
    deps:
      - data/processed/data_cleaned.csv
      - src/preprocessing/encode.py
    outs:
      - data/processed/data_encoded.csv

  scale:
    cmd: python src/preprocessing/scale.py
    deps:
      - data/processed/data_encoded.csv
      - src/preprocessing/scale.py
    outs:
      - data/processed/data_scaled.csv

  split:
    cmd: python src/preprocessing/split.py
    deps:
      - data/processed/data_encoded.csv
      - src/preprocessing/split.py
    outs:
      - data/processed/train/X_train.csv
      - data/processed/test/X_test.csv
      - data/processed/train/y_train.csv
      - data/processed/test/y_test.csv

  train_rf:
    cmd: python src/training/rf.py
    deps:
      - data/processed/train/X_train.csv
      - data/processed/test/X_test.csv
      - data/processed/train/y_train.csv
      - data/processed/test/y_test.csv
    outs:
      - models/rf/random_forest_model.pkl
      - data/metrics/rf/rf_metrics.json

  train_xgboost:
    cmd: python src/training/train_xgboost.py
    deps:
      - data/processed/train/X_train.csv
      - data/processed/test/X_test.csv
      - data/processed/train/y_train.csv
      - data/processed/test/y_test.csv
    outs:
      - models/XGBoost/xgboost_model.pkl
      - data/metrics/xgboost/xgboost_metrics.json